---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - mysql-server
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      apt: update_cache=yes name=docker.io state=latest

    - name: pull an image
      command: "docker pull jmendes18/mbio-task3:1.0"

    - name: run task3 image
      command: "docker run -it -d --name task3 jmendes18/mbio-task3:1.0"