---
plugin: aws_ec2
aws_profile: default
regions:
  - eu-central-1
filters:
  tag:Name:
    - nginx*
  instance-state-name : running
keyed_groups:
    - prefix: module
      key: tags['module']
hostnames:
  - private-ip-address